### ISSUE TITLE
You put twice "&&" in build command TMEN packages.json

### ISSUE THREAD

**Issue by stasgm** [buildtip/create-web-app#57]
https://github.com/buildtip/create-web-app/blob/57f42070e9180fc1d284af5caeeed6f4bb8552ff/generators/app/templates/TMEN/package.json#L10

**Comment by anikethsaha** [comment]
Sorry my bad. 
Feel free to put a PR or I will change ASAP. 
Thanks a lot. :+1:

**Comment by anikethsaha** [comment]
Fixed
